name: Test
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install django
      - run: python manage.py makemigrations LegacySite
      - run: python manage.py migrate
      - run: bash import_dbs.sh
      - run: python -m venv djangoenv
      - run: source djangoenv/bin/activate
      - run: mkdir djangoenv/fixtures
      - run: python manage.py dumpdata djangoenv > djangoenv/fixtures/testdata.json
      - run: python manage.py test